name: Shaaft build

# scripts/build.sh needs
# bash, wget, zip, tar, coreutils

on:
  push:
    tags:
      - "[1-9].[0-9]+.[0-9]+"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_SCRIPT: ./scripts/build.sh

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Do not convert line endings on checkout
      run: git config --global core.autocrlf input

    - uses: actions/checkout@v3
      with:
        ref: main
        submodules: recursive
        fetch-depth: 0

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - uses: cygwin/cygwin-install-action@master
      with:
        packages: >-
          bash
          wget
          zip
          tar
          coreutils

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        C:\cygwin\bin\bash.exe ${{env.BUILD_SCRIPT}}
        mkdir -p shaaft-${{ github.ref_name }}
        cp build.oem.Release\game\Release\shaaft.exe shaaft-${{ github.ref_name }}
        cp resource.dat shaaft-${{ github.ref_name }}
        zip -9r shaaft-${{ github.ref_name }}-windows.zip shaaft-${{ github.ref_name }}

    # upload artifacts so the publish job below can download and then update latest release via Linux
    - uses: actions/upload-artifact@v3
      with:
        name: shaaft-win-build
        path: shaaft-${{ github.ref_name }}-windows.zip

  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        submodules: recursive
        fetch-depth: 0

    - name: Setup Macos dependencies
      run: |
        brew install wget zip bash coreutils

    - name: Build
      working-directory: ${{github.workspace}}
      run: |
        bash ${{env.BUILD_SCRIPT}}
        mkdir -p shaaft-${{ github.ref_name }}
        cp -a build.oem.Release\game\Release\shaaft.app shaaft-${{ github.ref_name }}
        cp resource.dat shaaft-${{ github.ref_name }}
        zip -9r shaaft-${{ github.ref_name }}-mac.zip shaaft-${{ github.ref_name }}

    # upload artifacts so the publish job below can download and then update latest release via Linux
    - uses: actions/upload-artifact@v3
      with:
        name: shaaft-mac-build
        path: shaaft-${{ github.ref_name }}-mac.zip

  publish:
    needs: [build-windows, build-mac]

    # one of the steps uses container action which is Linux only
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: shaaft-win-build
        
    - uses: actions/download-artifact@v3
      with:
        name: shaaft-mac-build

    - name: Publish release
      # see https://github.com/pyTooling/Actions/tree/main/releaser
      uses: pyTooling/Actions/releaser@main
      with:
        tag: ${{ github.ref_name }}
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          shaaft-${{ github.ref_name }}-windows.zip
          shaaft-${{ github.ref_name }}-mac.zip
